name: Mocaverse Raffle
on:
  workflow_dispatch:

jobs:
  raffle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Raffle
        run: python3 raffle.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Raffle Winners